# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main@sha256:4657746e238e554aa32d2b0d8c9beb53cbe297a2542168067742c47d43aba5ad

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture armhf && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
