# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main@sha256:e161623077a5b4004724e53f0a6622eed698d0ba5746d8880dafe7fdc9ac1e45

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture arm64 && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:arm64 pkg-config
