# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main@sha256:5db2a92c73d1251c5fb9de895928ef2551c08d0ec30b969cf7340ca3dd62ea81

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture arm64 && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:arm64 pkg-config
