# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:379eee7aa254912a803b558fe0742450dd32ca9749bc8b931927dafa2ce6e8d3

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture armhf && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
