# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:8f5f93b1f6161292066e9aa991163cd19be18429e3f11f5a5ba255be0120ee36

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture armhf && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
