FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.4

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture arm64 && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:arm64 pkg-config
