# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main@sha256:59edc7687f9161ada084f0a9ba315765cc628a5f5306d53d350ab5521ef55b6c

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture armhf && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
