# Pinning a "main" branch version until a stable release in ghcr
FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:839f9f0b8a04a5bab473a6c68e198455a3be5ee4025c50e4f20d19568e373e8b

# Install libdbus libraries and pkg-config
RUN dpkg --add-architecture armhf && \
	apt-get update && \
	apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
